In [ ]:
# 3. Úvod do lineární algebry

In [2]:
# Gaussova eliminační metoda

import numpy as np

def gaussova_eliminacni_metoda(A, b): # A = matice koeficientů neznámých, b = vektor výsledků jednotlivých rovnic soustavy
    # Získání počtu koeficientů (počet rovnic)
    pocet_rovnic = len(A)
    
    # Vytvoření rozšířené matice spojením matice A s vektorem b
    rozsirena_matice = np.column_stack((A, b)).astype(np.float64)   # přetypování na desetinné číslo
    print("Původní rozšířená matice:")
    display(rozsirena_matice)

    # Přímá eliminace
    for i in range(pocet_rovnic):
        # Eliminace prvků pod vedoucím prvkem 
        if rozsirena_matice[i, i] == 0.0:
            print("Dělíš nulou!!!")
        for j in range(i + 1, pocet_rovnic):
            pomer = rozsirena_matice[j, i] / rozsirena_matice[i, i]
            rozsirena_matice[j] -= pomer * rozsirena_matice[i]

    print("\nRozšířená matice v horním trojúhelníkovém tvaru:")
    print(rozsirena_matice)

    # Zpětná substituce
    x = np.zeros(pocet_rovnic)  # vytvoření pole x, naplněného nulovými hodnotami, za které se pak dosadí daná řešení
    for i in range(pocet_rovnic - 1, -1, -1): # procházení matice v horním trojúhelníkovém tvaru od posledního řádku k prvnímu
        x[i] = (rozsirena_matice[i, -1] - np.dot(rozsirena_matice[i, :-1], x)) / rozsirena_matice[i, i]  # zjištění daného řešení
    
    return x

A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])
b = np.array([8, -11, -3])

reseni = gaussova_eliminacni_metoda(A, b)
print("\nŘešení soustavy lineárních rovnic:")
print(reseni)
print("\nOvěření pomocí numpy.linalg.solve:")
print(np.linalg.solve(A, b))


Původní rozšířená matice:
[[  2.   1.  -1.   8.]
 [ -3.  -1.   2. -11.]
 [ -2.   1.   2.  -3.]]

Rozšířená matice v horním trojúhelníkovém tvaru:
[[ 2.   1.  -1.   8. ]
 [ 0.   0.5  0.5  1. ]
 [ 0.   0.  -1.   1. ]]

Řešení soustavy lineárních rovnic:
[ 2.  3. -1.]

Ověření pomocí numpy.linalg.solve:
[ 2.  3. -1.]


In [14]:

import numpy as np
def gaussova_eliminacni_metoda(A, b):
    pocet_rovnic = len(A)
    rozsirena_matice = np.column_stack((A, b)).astype(np.float64)  
    for i in range(pocet_rovnic):
        if rozsirena_matice[i, i] == 0.0:
            print("Dělíš nulou!!!")
        for j in range(i + 1, pocet_rovnic):
            pomer = rozsirena_matice[j, i] / rozsirena_matice[i, i]
            rozsirena_matice[j] -= pomer * rozsirena_matice[i]

    x = np.zeros(pocet_rovnic) 
    for i in range(pocet_rovnic - 1, -1, -1): 
        x[i] = (rozsirena_matice[i, -1] - np.dot(rozsirena_matice[i, :-1], x)) / rozsirena_matice[i, i] 
    
    return x
D = np.array([[2,2,-3,1],
              [1,2,4,2],
              [-1,1,-1,1],
              [1,-1,2,-2]])
d = np.array([3,5,1,-4])

reseni = gaussova_eliminacni_metoda(D,d)
print("\nŘešení soustavy lineárních rovnic:")
print(reseni)
print("\nOvěření pomocí numpy.linalg.solve:")
print(np.linalg.solve(D,d))



Řešení soustavy lineárních rovnic:
[ 1.00000000e+00 -1.00000000e+00 -6.57909941e-17  3.00000000e+00]

Ověření pomocí numpy.linalg.solve:
[ 1. -1.  0.  3.]


In [15]:

def jacobiho_iteracni_metoda(A, b, pocet_iteraci, pocatek=np.ones(len(A))): # A = matice koeficientů SLR, b = vektor pravých stran SLR, pocatek = vektor plný jedniček
    x = pocatek
    D = np.diag(A)  # prvky z diagonály
    L = np.tril(A, k = -1)  # prvky pod diagonálou
    U = np.triu(A, k = 1) # prvky nad diagonálou
    for i in range(pocet_iteraci):
        x = (b - np.matmul(L, x) - np.matmul(U, x)) / D
        print("iterace:",i, "x=",x)
    return x

D = np.array([[2,2,-3,1],
              [1,2,4,2],
              [-1,1,-1,1],
              [1,-1,2,-2]])
d = np.array([3,5,1,-4])

x = jacobiho_iteracni_metoda(D,d, 20)
print("reseni: ", x)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 4)

In [ ]:
A = np.array([[1]])
a = np.array([2])

B = np.array([[1,1],
             [2,-1]])
b = np.array([8,1])

C = np.array([[3,-2,5],
              [1,1,2],
              [-2,1,-6]])
c = np.array([-7,4,6])

D = np.array([[2,2,-3,1],
              [1,2,4,2],
              [-1,1,-1,1],
              [1,-1,2,-2]])
d = np.array([3,5,1,-4])





###############################################################################################################xx

import numpy as np
def gaussova_eliminacni_metoda(A, b):
    pocet_rovnic = len(A)
    rozsirena_matice = np.column_stack((A, b)).astype(np.float64)  
    for i in range(pocet_rovnic):
        if rozsirena_matice[i, i] == 0.0:
            print("Dělíš nulou!!!")
        for j in range(i + 1, pocet_rovnic):
            pomer = rozsirena_matice[j, i] / rozsirena_matice[i, i]
            rozsirena_matice[j] -= pomer * rozsirena_matice[i]

    x = np.zeros(pocet_rovnic) 
    for i in range(pocet_rovnic - 1, -1, -1): 
        x[i] = (rozsirena_matice[i, -1] - np.dot(rozsirena_matice[i, :-1], x)) / rozsirena_matice[i, i] 
    
    return x

###############################################################################################################
A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])
b = np.array([8, -11, -3])

reseni = gaussova_eliminacni_metoda(A, b)
print("\nŘešení soustavy lineárních rovnic:")
print(reseni)
print("\nOvěření pomocí numpy.linalg.solve:")
print(np.linalg.solve(A, b))


def jacobiho_iteracni_metoda(A, b, pocet_iteraci, pocatek=np.ones(len(A))): # A = matice koeficientů SLR, b = vektor pravých stran SLR, pocatek = vektor plný jedniček
    x = pocatek
    D = np.diag(A)  # prvky z diagonály
    L = np.tril(A, k = -1)  # prvky pod diagonálou
    U = np.triu(A, k = 1) # prvky nad diagonálou
    for i in range(pocet_iteraci):
        x = (b - np.matmul(L, x) - np.matmul(U, x)) / D
        print("iterace:",i, "x=",x)
    return x

A = np.array([
    [2, 1], 
    [5, 7]
])
b = np.array([11, 13])

x = jacobiho_iteracni_metoda(A, b, 20)
print("reseni: ", x)



In [27]:
import numpy as np

def gauss_seidel(A, b, n_iteraci, x0=np.zeros(4)):
    x = x0.copy()
    L_star = np.tril(A)               # D + L
    U = np.triu(A, k=1)               # Horní trojúhelníková matice
    T = -np.linalg.inv(L_star).dot(U)   # T = -inv(L*).U
    C = np.linalg.inv(L_star).dot(b)   # C = inv(L*).b
    for i in range(n_iteraci):
        x = T.dot(x) + C                  # x = Tx + C
    return x

D = np.array([[2, 2, -3, 1],
              [1, 2, 4, 2],
              [-1, 1, -1, 1],
              [1, -1, 2, -2]])
d = np.array([3, 5, 1, -4])

x = gauss_seidel(D, d, 20)
print("Výsledek Gauss-Seidelovy metody:", x)


Výsledek Gauss-Seidelovy metody: [-2507855.97142656 30678408.51812739 28170556.54670083 11577426.30192386]


In [43]:
def gauss_seidel(A, b, tolerance=1e-10, max_iterations=10000):
    
    x = np.zeros_like(b, dtype=np.double)
    
    #Iterate
    for k in range(max_iterations):
        
        x_old  = x.copy()
        
        #Loop over rows
        for i in range(A.shape[0]):
            x[i] = (b[i] - np.dot(A[i,:i], x[:i]) - np.dot(A[i,(i+1):], x_old[(i+1):])) / A[i ,i]
            
        #Stop condition 
        if np.linalg.norm(x - x_old, ord=np.inf) / np.linalg.norm(x, ord=np.inf) < tolerance:
            break
            
    return x

D = np.array([[2, 2, -3, 1],
              [1, 2, 4, 2],
              [-1, 1, -1, 1],
              [1, -1, 2, -2]])
d = np.array([3, 5, 1, -4])
print(gauss_seidel(D,d,0.1,100))


[-2.89507139e+35  3.54152000e+36  3.25201287e+36  1.33649929e+36]
